
DEV_EUI = "XXXXXXXXXXXXXXXX"  # Your DevEUI
APP_EUI = "XXXXXXXXXXXXXXXX"  # Can be all zeros for TTN
APP_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  # Your AppKey
LORA_INITIAL_TIME = 210 # Seconds
LORA_INTERVAL_TIME = 30 # Seconds
